### ISSUE TITLE
自動ビルドされたwindows CPU版のVOICEVOXを起動できない

### ISSUE THREAD

**Issue by Hiroshiba** [Hiroshiba/voicevox#299]
## 不具合の内容

windowsのCPU版VOICEVOXを実行しようとしてみたところ、エンジン起動でエラーが表示されました。

### 現象・ログ

```bash
[02:15:37.331] [error] ENGINE: Traceback (most recent call last):
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\run.py", line 424, in <module>
  File "C:\Users\hihok\DOWNLO~1\WINDOW~1\run.py", line 77, in make_synthesis_engine
  File "core.pyx", line 6, in core.initialize
  File "core.pyx", line 14, in core.initialize
Exception: Could not run 'aten::empty_strided' with arguments from the 'CUDA' backend. This could be because th...

[02:15:38.409] [error] Error: Failed to fetch Failed to fetch AudioQuery for the text "".
[02:15:38.412] [error] TypeError: Failed to fetch
```

### 再現手順

https://github.com/Hiroshiba/voicevox/actions/runs/1300761100 の`windows-cpu-prepackage`をダウンロードしてVOICEVOX.exeをダブルクリック

## VOICEVOXのバージョン

0.?.0

## その他

GPU版は問題なく動きました

**Comment by aoirint** [comment]
GPUの載っていないCPUマシンで
https://github.com/Hiroshiba/voicevox/actions/runs/1300761100 の `windows-cpu-prepackage` の
`VOICEVOX.exe` 起動を試してみましたが、エンジンの起動・音声合成まで問題なく動作しました。

エンジンの起動モードがGPUになっているか、GPUの載っているマシンで起きる問題かなと思いました。
前者は、設定ファイルがGPU版・CPU版で共通なためだと思います。

#298 と関連しそうですが、CPU版はコアがGPUモードに対応していないので、VOICEVOX側はCPUモードに固定するような実装をしてもよさそうです。
コア（話者）に起動モードの候補リストを返すようなAPIがほしいかもしれません。

**Comment by Hiroshiba** [comment]
> エンジンの起動モードがGPUになっている

いやーーーーお恥ずかしい、そのとおりでした・・・。

> コア（話者）に起動モードの候補リストを返すようなAPIがほしいかもしれません。
